language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - phpenv config-add config.ini
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - php bin/phpunit --verbose --coverage-text --coverage-clover /tmp/flysystem/coverage.xml; fi;'
